### ISSUE TITLE
bug-report: v0.170.6 crashes when rendering fields with hint

### ISSUE THREAD

**Issue by jiazengp** [sveltia/sveltia-cms#818]
After upgrading Sveltia CMS from v0.170.5 to v0.170.6, the entry editor crashes when rendering a field that has the hint option configured.

The same configuration works correctly with v0.170.5.

The browser console reports:

```
Uncaught TypeError: n is not a function at field-editor.svelte:356 at field-editor.svelte:350 at field-editor.svelte:352 at field-editor-group.svelte:33 at field-editor.svelte:252 at field-editor.svelte:251 at field-editor.svelte:305 at entry-editor.svelte:32 at visibility-observer.svelte:32 at visibility-observer.svelte:35
```

## Environment

- Sveltia CMS: v0.170.6
- Last known working version: v0.170.5
- Browser: Chrome 152
- Operating system: Windows 11

**Comment by kyoshino** [comment]
Will check 🙏🏼

**Comment by kyoshino** [comment]
Fixed in [v0.170.7](https://github.com/sveltia/sveltia-cms/releases/tag/v0.170.7) 🙇🏼
